### ISSUE TITLE
Need puzzles for bonuses

### ISSUE THREAD

**Issue by LunarGem** [LunarGem/fire-and-ice#27]
In the tavern and sometimes after letting an enemy go, you can get a puzzle you can solve for a bonus (any other drop, x10 or rare items). Any ideas can be placed here!

**Comment by Suds-p** [comment]
Any ripoffs of:
- Bejeweled
- Slide puzzles
- Rotating tiles puzzles
- Ciphers
- Any sort of infinite collectible mini-game
- Memory games
- Tangrams of medieval-ish shapes...

All of which are probs super complicated to implement, lol. Maybe the rotating puzzle shouldn't be that bad...

**Comment by LunarGem** [comment]
Maybe some sort of algebra puzzle disguised as spell combination that could actually be a cheat code?

**Comment by Suds-p** [comment]
Oh, that would be interesting. You mean like filling in equations and stuff?

**Comment by LunarGem** [comment]
Idk what I mean anymore... it seemed better formed an hour ago 😝 
EDIT: That's not exactly the emoji I was going for, more like XP but...
