### ISSUE TITLE
Fix rest function

### ISSUE THREAD

**Issue by LunarGem** [LunarGem/fire-and-ice#8]
So, when you click the rest function currently, the timer parts don't work, it just goes up by 10 each time you click (and it won't stop once your bar is full...). I want it so you can click once and it rests by itself, increasing your health every second by 5 or 10, and you can do anything but train and fight during that time. Think you can figure out why this isn't working the way it should? Thanks.

**Comment by Suds-p** [comment]
Think I may have figured it out (surprisingly :P). 
Couple issues here:
- `setTimeout()` should take a function as a parameter, but `upHealth(currHealthRate)` just gives you the value returned by it, which is undefined. It still ran `upHealth()`, but didn't attach the delay for some reason...
- In that case, I put the `upHealth()` call into a new function object: 
`setTimeout(function() {upHealth(...);}, 2000)`
Still didn't work cause, somehow, and I kept getting infinite loops. Maybe setTimeout() just gets really finicky in loops...

Solution:
- I looked at the sibling function `setInterval()` for a solution (same syntax as `setTimeout()`), and even though this infinitely calls a function every x milliseconds, you can use `clearTimeout()` to remove that effect. 
```javascript
function rest(){
    // Solution from: http://stackoverflow.com/a/1495907/6447865
    timeoutID = setInterval(function () {
		upHealth(currHealthRate);

        if($('#health').attr("aria-valuenow") >= maxHealth){
		console.log("done resting");
		$('#health').attr("aria-valuenow", maxHealth);
		clearInterval(timeoutID);
	}
    }, 2000);
}
```
The `timeoutID` stuff was needed for `clearInterval()` to figure out exactly who to remove the effect from.

**Comment by Suds-p** [comment]
Still a few issues with the solution, like multiple "timers" set on the health bar if you clicked the Rest button multiple times. Not quite sure how to fix that yet, but it might just need a simple condition or two.

Solution's on my branch, though I don't wanna pull just yet cause of all the JS stuff I moved around :S. Not sure if it would conflict or somethin...

**Comment by LunarGem** [comment]
Thanks! I really had no clue what I was doing (copied code from the internet and wondered what I was doing wrong XD). I'll keep working on the UI and then when it's navigable work on that.

**Comment by Suds-p** [comment]
Sounds good! I'll see if I can make this a bit more robust, but glad I could help :3.

**Comment by Suds-p** [comment]
Ok, I made the 'resting' boolean flag global, so multiple clicks shouldn't bother the current resting ticker now. Current solution should be available.

**Comment by LunarGem** [comment]
Great! I shouldn't be working on this until my lunch break, so I'll check it out then.

**Comment by Suds-p** [comment]
This isn't related, but is it ok if I added a gitignore to the project? Just so that my pesky IDE files don't get mixed into the repo...

**Comment by LunarGem** [comment]
I'd have no clue what that does so use your best judgement. 😛 Hey look an emoji!

**Comment by Suds-p** [comment]
Found another one 🤓, lol. gitignores just make sure that some types of files (like extraneous IDE stuff) doesn't get added into your repos. As the name suggests, you can list a bunch of files and file types for it to "ignore".

**Comment by LunarGem** [comment]
Totally fine by me (I'm sure I'm not using it, I use NP++).

**Comment by LunarGem** [comment]
Apparently because of the multiple rest check, it never stops resting (never leaves the function) and nothing after that can happen. I don't really want to mess with your code, so maybe you can deal with this in your own time. 😃

**Comment by Suds-p** [comment]
Ahh yeah. Was gonna ask about that. Should it stop resting if the player clicks the button again?

**Comment by LunarGem** [comment]
I don't know. I feel like it should stop once it's finished an only then... maybe the loop just needs a break command in it somewhere.

**Comment by Suds-p** [comment]
~Hmm I noticed that, while getting attacked, the health doesn't get depleted when it's resting, so I'll have to fix that...~ Nvm, didn't notice that the enemy already died...

Right now, it seems to continue resting until the health's maxed out.
Should I still allow the player to stop resting if they click the button again?

**Comment by LunarGem** [comment]
Sure, maybe change the button text to "Stop Resting", too?

**Comment by Suds-p** [comment]
Yep, wanted to add that as well :3.

**Comment by LunarGem** [comment]
I think 03e3353 closes this but if you have more changes you want to make feel free. ;)
